[repositories."getwilds/ww-fastq-to-cram"]
identifier = "getwilds/ww-fastq-to-cram"
commit_hash = "7dd6c4c7c8c9fc6dcd4eb5ff8f3262cd26d5e7cc"

[repositories."stjudecloud/workflows"]
identifier = "stjudecloud/workflows"
commit_hash = "84bd23756563f32d144f11aa2e82a76e059a8b61"
filters = ["/template/task-templates.wdl"]

[[diagnostics]]
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "ww-fastq-to-cram.wdl:129:5: note[MatchingParameterMeta]: task `FastqToUnmappedBam` has an extraneous parameter metadata key named `unmapped_bam`"

[[diagnostics]]
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "ww-fastq-to-cram.wdl:134:6: warning[SnakeCase]: task name `ValidateCram` is not snake_case"

[[diagnostics]]
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "ww-fastq-to-cram.wdl:165:5: note[MatchingParameterMeta]: task `ValidateCram` has an extraneous parameter metadata key named `validation`"

[[diagnostics]]
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "ww-fastq-to-cram.wdl:170:6: warning[SnakeCase]: task name `MergeBamsToCram` is not snake_case"

[[diagnostics]]
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "ww-fastq-to-cram.wdl:202:5: note[MatchingParameterMeta]: task `MergeBamsToCram` has an extraneous parameter metadata key named `cram`"

[[diagnostics]]
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "ww-fastq-to-cram.wdl:203:5: note[MatchingParameterMeta]: task `MergeBamsToCram` has an extraneous parameter metadata key named `crai`"

[[diagnostics]]
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "ww-fastq-to-cram.wdl:205:1: warning[EndingNewline]: missing newline at the end of the file"

[[diagnostics]]
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "ww-fastq-to-cram.wdl:23:10: warning[SnakeCase]: workflow name `PairedFastqsToUnmappedCram` is not snake_case"

[[diagnostics]]
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "ww-fastq-to-cram.wdl:57:13: warning[Whitespace]: line contains trailing whitespace"

[[diagnostics]]
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "ww-fastq-to-cram.wdl:74:5: note[MatchingParameterMeta]: workflow `PairedFastqsToUnmappedCram` has an extraneous parameter metadata key named `unmapped_crams`"

[[diagnostics]]
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "ww-fastq-to-cram.wdl:75:5: note[MatchingParameterMeta]: workflow `PairedFastqsToUnmappedCram` has an extraneous parameter metadata key named `unmapped_cram_indexes`"

[[diagnostics]]
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "ww-fastq-to-cram.wdl:76:5: note[MatchingParameterMeta]: workflow `PairedFastqsToUnmappedCram` has an extraneous parameter metadata key named `validation`"

[[diagnostics]]
document = "getwilds/ww-fastq-to-cram:/ww-fastq-to-cram.wdl"
message = "ww-fastq-to-cram.wdl:83:6: warning[SnakeCase]: task name `FastqToUnmappedBam` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "read_group.wdl:32:12: warning[SnakeCase]: struct member name `ID` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "read_group.wdl:33:13: warning[SnakeCase]: struct member name `BC` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "read_group.wdl:34:13: warning[SnakeCase]: struct member name `CN` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "read_group.wdl:35:13: warning[SnakeCase]: struct member name `DS` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "read_group.wdl:36:13: warning[SnakeCase]: struct member name `DT` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "read_group.wdl:37:13: warning[SnakeCase]: struct member name `FO` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "read_group.wdl:38:13: warning[SnakeCase]: struct member name `KS` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "read_group.wdl:39:13: warning[SnakeCase]: struct member name `LB` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "read_group.wdl:40:13: warning[SnakeCase]: struct member name `PG` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "read_group.wdl:41:10: warning[SnakeCase]: struct member name `PI` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "read_group.wdl:42:13: warning[SnakeCase]: struct member name `PL` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "read_group.wdl:43:13: warning[SnakeCase]: struct member name `PM` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "read_group.wdl:44:13: warning[SnakeCase]: struct member name `PU` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/data_structures/read_group.wdl"
message = "read_group.wdl:45:13: warning[SnakeCase]: struct member name `SM` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/tools/gatk4.wdl"
message = "gatk4.wdl:107:14: warning[SnakeCase]: input name `dbSNP_vcf` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/tools/gatk4.wdl"
message = "gatk4.wdl:108:14: warning[SnakeCase]: input name `dbSNP_vcf_index` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/tools/gatk4.wdl"
message = "gatk4.wdl:249:14: warning[SnakeCase]: input name `dbSNP_vcf` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/tools/gatk4.wdl"
message = "gatk4.wdl:250:14: warning[SnakeCase]: input name `dbSNP_vcf_index` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/tools/star.wdl"
message = "star.wdl:552:13: warning[SnakeCase]: input name `out_QS_conversion_add` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/tools/star.wdl"
message = "star.wdl:553:13: warning[SnakeCase]: input name `out_sam_attr_IH_start` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/tools/star.wdl"
message = "star.wdl:555:13: warning[SnakeCase]: input name `out_sam_flag_OR` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/tools/star.wdl"
message = "star.wdl:556:13: warning[SnakeCase]: input name `out_sam_flag_AND` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/tools/star.wdl"
message = "star.wdl:564:13: warning[SnakeCase]: input name `score_gap_GCAG` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/tools/star.wdl"
message = "star.wdl:565:13: warning[SnakeCase]: input name `score_gap_ATAC` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/tools/star.wdl"
message = "star.wdl:597:13: warning[SnakeCase]: input name `chim_score_junction_nonGTAG` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/tools/star.wdl"
message = "star.wdl:61:13: warning[SnakeCase]: input name `genome_SA_index_n_bases` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/tools/star.wdl"
message = "star.wdl:62:13: warning[SnakeCase]: input name `genome_SA_sparse_d` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/tools/star.wdl"
message = "star.wdl:818:9: warning[SnakeCase]: struct member name `GT_AG_and_CT_AC_motif` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/tools/star.wdl"
message = "star.wdl:819:9: warning[SnakeCase]: struct member name `GC_AG_and_CT_GC_motif` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/tools/star.wdl"
message = "star.wdl:820:9: warning[SnakeCase]: struct member name `AT_AC_and_GT_AT_motif` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/workflows/reference/gatk-reference.wdl"
message = "gatk-reference.wdl:101:15: warning[SnakeCase]: output name `dbSNP_vcf` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/workflows/reference/gatk-reference.wdl"
message = "gatk-reference.wdl:102:15: warning[SnakeCase]: output name `dbSNP_vcf_index` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/workflows/reference/gatk-reference.wdl"
message = "gatk-reference.wdl:40:16: warning[SnakeCase]: input name `dbSNP_vcf_url` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/workflows/reference/gatk-reference.wdl"
message = "gatk-reference.wdl:41:16: warning[SnakeCase]: input name `dbSNP_vcf_name` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/workflows/reference/gatk-reference.wdl"
message = "gatk-reference.wdl:42:17: warning[SnakeCase]: input name `dbSNP_vcf_index_url` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/workflows/reference/gatk-reference.wdl"
message = "gatk-reference.wdl:43:17: warning[SnakeCase]: input name `dbSNP_vcf_index_name` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/workflows/rnaseq/rnaseq-core.wdl"
message = "rnaseq-core.wdl:138:13: warning[SnakeCase]: input name `chim_score_junction_nonGTAG` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/workflows/rnaseq/rnaseq-variant-calling.wdl"
message = "rnaseq-variant-calling.wdl:42:14: warning[SnakeCase]: input name `dbSNP_vcf` is not snake_case"

[[diagnostics]]
document = "stjudecloud/workflows:/workflows/rnaseq/rnaseq-variant-calling.wdl"
message = "rnaseq-variant-calling.wdl:43:14: warning[SnakeCase]: input name `dbSNP_vcf_index` is not snake_case"
