[workspace]
members = [
    "ci",
    "gauntlet",
    "wdl",
    "wdl-analysis",
    "wdl-ast",
    "wdl-doc",
    "wdl-engine",
    "wdl-format",
    "wdl-grammar",
    "wdl-lint",
    "wdl-lsp",
]
resolver = "2"

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2021"
authors = ["The Rust WDL project developers"]
homepage = "https://github.com/stjude-rust-labs/wdl"
repository = "https://github.com/stjude-rust-labs/wdl"
rust-version = "1.82.0"

[workspace.dependencies]
anyhow = "1.0.86"
approx = "0.5.1"
clap = { version = "4.5.7", features = ["derive"] }
clap-verbosity-flag = "2.2.1"
codespan-reporting = "0.11.1"
colored = "2.1.0"
convert_case = "0.6.0"
dirs = "5.0.1"
faster-hex = "0.9.0"
ftree = "1.2.0"
futures = "0.3.30"
git2 = "0.18.3"
glob = "0.3.1"
indexmap = { version = "2.2.6", features = ["serde"] }
indicatif = "0.17.8"
itertools = "0.13.0"
line-index = "0.1.1"
logos = "0.14.0"
nonempty = "0.10.0"
ordered-float = "4.3.0"
parking_lot = "0.12.3"
path-clean = "1.0.1"
petgraph = "0.6.5"
pretty_assertions = "1.4.0"
rand = "0.8.5"
rayon = "1.10.0"
regex = "1.11.1"
reqwest = { version = "0.12.5", default-features = false, features = ["rustls-tls", "http2", "charset"] }
rowan = "0.15.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.120"
serde_with = "3.8.1"
sysinfo = "0.32.1"
tempfile = "3.10.1"
tokio = { version = "1.38.0", features = ["full"] }
toml = "0.8.14"
tower-lsp = "0.20.0"
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5.2"
urlencoding = "2.1.3"
uuid = "1.10.0"
walkdir = "2.5.0"
webbrowser = "1.0.3"

[workspace.lints.rust]
missing_docs = "warn"
nonstandard-style = "warn"
rust-2018-idioms = "warn"
rust-2021-compatibility = "warn"

# Re-enable this lint and remove the group expansion lints after auditing remaining diagnostics as we get closer to the 2024 release
# rust-2024-compatibility = "warn"
# <expansion>
boxed-slice-into-iter = "warn"
dependency-on-unit-never-type-fallback = "warn"
deprecated-safe-2024 = "warn"
edition-2024-expr-fragment-specifier = "allow"  # Reason: the few macros where we use the `expr` fragment will not break with the new expressions
if-let-rescope = "allow"                        # Reason: lint is too noisy and we are unlikely to have drop order dependencies
impl-trait-overcaptures = "warn"
keyword-idents-2024 = "warn"
missing-unsafe-on-extern = "warn"
never-type-fallback-flowing-into-unsafe = "warn"
rust-2024-guarded-string-incompatible-syntax = "warn"
rust-2024-incompatible-pat = "warn"
rust-2024-prelude-collisions = "warn"
static-mut-refs = "warn"
tail-expr-drop-order = "allow"                  # Reason: lint is too noisy and we are unlikely to have drop order dependencies
unsafe-attr-outside-unsafe = "warn"
unsafe-op-in-unsafe-fn  = "warn"
# </expansion>

[workspace.lints.rustdoc]
broken_intra_doc_links = "warn"

[workspace.lints.clippy]
missing_docs_in_private_items = "warn"
