[workspace]
members = [
    "wdl",
    "wdl-analysis",
    "wdl-ast",
    "wdl-gauntlet",
    "wdl-grammar",
    "wdl-lint",
    "wdl-lsp",
]
resolver = "2"

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2021"
authors = ["The Rust WDL project developers"]
homepage = "https://github.com/stjude-rust-labs/wdl"
repository = "https://github.com/stjude-rust-labs/wdl"
rust-version = "1.80.0"

[workspace.dependencies]
clap = { version = "4.5.7", features = ["derive"] }
colored = "2.1.0"
convert_case = "0.6.0"
env_logger = "0.11.3"
indexmap = { version = "2.2.6", features = ["serde"] }
log = "0.4.21"
regex = "1.10.5"
serde = { version = "1", features = ["derive"] }
serde_with = "3.8.1"
tokio = { version = "1.38.0", features = ["full"] }
toml = "0.8.14"
logos = "0.14.0"
rowan = "0.15.15"
pretty_assertions = "1.4.0"
rayon = "1.10.0"
approx = "0.5.1"
codespan-reporting = "0.11.1"
anyhow = "1.0.86"
dirs = "5.0.1"
faster-hex = "0.9.0"
git2 = "0.18.3"
tempfile = "3.10.1"
url = "2.5.2"
urlencoding = "2.1.3"
parking_lot = "0.12.3"
reqwest = "0.12.5"
petgraph = "0.6.5"
futures = "0.3.30"
walkdir = "2.5.0"
path-clean = "1.0.1"
indicatif = "0.17.8"
tower-lsp = "0.20.0"
line-index = "0.1.1"
serde_json = "1.0.120"
uuid = "1.10.0"
id-arena = "2.2.1"
