[workspace]
members = [
    "wdl",
    "wdl-ast",
    "wdl-core",
    "wdl-gauntlet",
    "wdl-grammar",
    "wdl-lint",
    "wdl-macros",
]
resolver = "2"

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2021"
version = "0.3.0"
authors = ["The Rust WDL project developers"]
homepage = "https://github.com/stjude-rust-labs/wdl"
repository = "https://github.com/stjude-rust-labs/wdl"

[workspace.dependencies]
clap = { version = "4.4.7", features = ["derive"] }
colored = "2.0.4"
convert_case = "0.6.0"
env_logger = "0.10.0"
indexmap = { version = "2.1.0", features = ["serde"] }
lazy_static = "1.4.0"
log = "0.4.20"
nonempty = { version = "0.9.0", features = ["serialize"] }
ordered-float = "4.2.0"
pest = { version = "2.7.5", features = ["pretty-print"] }
pest_derive = "2.7.5"
regex = "1.10.2"
serde = { version = "1", features = ["derive"] }
serde_with = "3.4.0"
tokio = { version = "1.33.0", features = ["full"] }
toml = "0.8.8"
logos = "0.14.0"
rowan = "0.15.15"
pretty_assertions = "1.4.0"
rayon = "1.10.0"
approx = "0.5.1"
codespan-reporting = "0.11.1"
anyhow = "1.0.86"
dirs = "5.0.1"
faster-hex = "0.9.0"
git2 = "0.18.3"
temp-dir = "0.1.13"
