version = "v1"

[[repositories]]
organization = "PacificBiosciences"
name = "HiFi-human-WGS-WDL"

[[repositories]]
organization = "biowdl"
name = "tasks"

[[repositories]]
organization = "broadinstitute"
name = "warp"

[[repositories]]
organization = "chanzuckerberg"
name = "czid-workflows"

[[repositories]]
organization = "stjudecloud"
name = "workflows"

[[concerns]]
kind = "ParseError"
document = "broadinstitute/warp:pipelines/broad/dna_seq/germline/single_sample/ugwgs/UltimaGenomicsWholeGenomeGermline.wdl"
message = "The following tokens are required: comma. (126:5)"

[[concerns]]
kind = "ParseError"
document = "broadinstitute/warp:tasks/broad/Funcotator.wdl"
message = "The following tokens are required: whitespace, comment. (120:78)"

[[concerns]]
kind = "ParseError"
document = "broadinstitute/warp:tasks/broad/GermlineVariantDiscovery.wdl"
message = "The following tokens are required: string. (65:32)"

[[concerns]]
kind = "ParseError"
document = "broadinstitute/warp:tasks/broad/InternalTasks.wdl"
message = "The following tokens are required: whitespace, comment. (64:77)"

[[concerns]]
kind = "ParseError"
document = "broadinstitute/warp:tasks/broad/SplitLargeReadGroup.wdl"
message = "The following tokens are required: comma. (48:5)"

[[concerns]]
kind = "ParseError"
document = "broadinstitute/warp:tasks/broad/UltimaGenomicsWholeGenomeGermlineAlignmentMarkDuplicates.wdl"
message = "The following tokens are required: comma. (56:7)"

[[concerns]]
kind = "ParseError"
document = "broadinstitute/warp:tasks/broad/UltimaGenomicsWholeGenomeGermlineTasks.wdl"
message = "The following tokens are required: string. (814:27)"

[[concerns]]
kind = "ParseError"
document = "broadinstitute/warp:tasks/skylab/FastqProcessing.wdl"
message = "The following tokens are not allowed: space. (162:12)"

[[concerns]]
kind = "ParseError"
document = "broadinstitute/warp:tests/cemba/pr/CheckCembaOutputs.wdl"
message = "The following tokens are required: document. (1:1)"

[[concerns]]
kind = "ParseError"
document = "broadinstitute/warp:verification/VerifyTasks.wdl"
message = "The following tokens are required: or, and, add, sub, mul, div, remainder, eq, neq, lte, gte, lt, gt. (75:119)"

[[concerns]]
kind = "ParseError"
document = "stjudecloud/workflows:template/task-templates.wdl"
message = "The following tokens are required: expression. (49:35)"

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:bcftools.wdl"
message = '''[v1::E001] invalid escape character: '\_' (114:75-114:77)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:bedtools.wdl"
message = '''[v1::E001] invalid escape character: '\.' (27:48-27:50)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:bowtie.wdl"
message = '''[v1::E001] invalid escape character: '\.' (63:32-63:34)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:bowtie.wdl"
message = '''[v1::E001] invalid escape character: '\.' (63:39-63:41)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:bowtie.wdl"
message = '''[v1::E001] invalid escape character: '\.' (63:46-63:48)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:bowtie.wdl"
message = '''[v1::E001] invalid escape character: '\.' (75:48-75:50)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:centrifuge.wdl"
message = '''[v1::E001] invalid escape character: '\.' (122:57-122:59)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:centrifuge.wdl"
message = '''[v1::E001] invalid escape character: '\.' (122:64-122:66)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:centrifuge.wdl"
message = '''[v1::E001] invalid escape character: '\.' (199:57-199:59)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:centrifuge.wdl"
message = '''[v1::E001] invalid escape character: '\.' (199:64-199:66)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:centrifuge.wdl"
message = '''[v1::E001] invalid escape character: '\.' (256:57-256:59)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:centrifuge.wdl"
message = '''[v1::E001] invalid escape character: '\.' (256:64-256:66)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:common.wdl"
message = '''[v1::E001] invalid escape character: '\.' (275:45-275:47)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:fastqc.wdl"
message = '''[v1::E001] invalid escape character: '\.' (59:42-59:44)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:fastqc.wdl"
message = '''[v1::E001] invalid escape character: '\.' (63:54-63:56)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:fastqc.wdl"
message = '''[v1::E001] invalid escape character: '\.' (63:58-63:60)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:gatk.wdl"
message = '''[v1::E001] invalid escape character: '\.' (127:57-127:59)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:gatk.wdl"
message = '''[v1::E001] invalid escape character: '\.' (1597:41-1597:43)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:hisat2.wdl"
message = '''[v1::E001] invalid escape character: '\.' (60:34-60:36)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:hisat2.wdl"
message = '''[v1::E001] invalid escape character: '\.' (60:41-60:43)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:multiqc.wdl"
message = '''[v1::E001] invalid escape character: '\.' (133:45-133:47)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:picard.wdl"
message = '''[v1::E001] invalid escape character: '\.' (1021:48-1021:50)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:picard.wdl"
message = '''[v1::E001] invalid escape character: '\.' (1191:48-1191:50)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:picard.wdl"
message = '''[v1::E001] invalid escape character: '\.' (643:51-643:53)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:picard.wdl"
message = '''[v1::E001] invalid escape character: '\.' (785:51-785:53)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:picard.wdl"
message = '''[v1::E001] invalid escape character: '\.' (900:46-900:48)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:picard.wdl"
message = '''[v1::E001] invalid escape character: '\.' (901:46-901:48)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:picard.wdl"
message = '''[v1::E001] invalid escape character: '\.' (902:49-902:51)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:sambamba.wdl"
message = '''[v1::E001] invalid escape character: '\.' (145:49-145:51)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:sambamba.wdl"
message = '''[v1::E001] invalid escape character: '\.' (157:60-157:62)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:sambamba.wdl"
message = '''[v1::E001] invalid escape character: '\.' (91:44-91:46)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:samtools.wdl"
message = '''[v1::E001] invalid escape character: '\.' (238:53-238:55)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:samtools.wdl"
message = '''[v1::E001] invalid escape character: '\.' (326:44-326:46)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:samtools.wdl"
message = '''[v1::E001] invalid escape character: '\.' (414:44-414:46)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:samtools.wdl"
message = '''[v1::E001] invalid escape character: '\.' (458:49-458:51)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:samtools.wdl"
message = '''[v1::E001] invalid escape character: '\.' (470:60-470:62)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:samtools.wdl"
message = '''[v1::E001] invalid escape character: '\.' (80:42-80:44)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:umi-tools.wdl"
message = '''[v1::E001] invalid escape character: '\.' (95:49-95:51)'''

[[concerns]]
kind = "ValidationFailure"
document = "biowdl/tasks:umi.wdl"
message = '''[v1::E001] invalid escape character: '\.' (39:60-39:62)'''

[[concerns]]
kind = "ValidationFailure"
document = "broadinstitute/warp:pipelines/skylab/scATAC/scATAC.wdl"
message = "[v1::E003] duplicate runtime keys: 'cpu' (199:9-199:12, 203:9-203:12)"

[[concerns]]
kind = "ValidationFailure"
document = "chanzuckerberg/czid-workflows:workflows/index-generation/index-generation.wdl"
message = "[v1::E002] invalid version: 'version development' (1:1-1:20)"
