[repositories."ENCODE-DCC/chip-seq-pipeline2"]
identifier = "ENCODE-DCC/chip-seq-pipeline2"
commit_hash = "26eeda81a0540dc793fc69b0c390d232ca7ca50a"

[repositories."PacificBiosciences/HiFi-human-WGS-WDL"]
identifier = "PacificBiosciences/HiFi-human-WGS-WDL"
commit_hash = "9a1a2846443e4b621f1dca0259fd3fa21885156a"

[repositories."aws-samples/amazon-omics-tutorials"]
identifier = "aws-samples/amazon-omics-tutorials"
commit_hash = "0a49b4326f67ac72150159a183084a252cf45ee0"

[repositories."biowdl/tasks"]
identifier = "biowdl/tasks"
commit_hash = "2bf875300d90a3c9c8d670b3d99026452d5dbae2"

[repositories."broadinstitute/gatk-tool-wdls"]
identifier = "broadinstitute/gatk-tool-wdls"
commit_hash = "04057c175d0307f96f3f90e2704a4594ebf4e314"

[repositories."broadinstitute/palantir-workflows"]
identifier = "broadinstitute/palantir-workflows"
commit_hash = "1e32078d3b57dcb2291534d0caa30f600d40967e"

[repositories."broadinstitute/warp"]
identifier = "broadinstitute/warp"
commit_hash = "f094475689311ccf227b39b5f40b70762889566c"

[repositories."chanzuckerberg/czid-workflows"]
identifier = "chanzuckerberg/czid-workflows"
commit_hash = "15f611d382212519310a1187ef3fd0e96fe3ef21"

[repositories."getwilds/ww-fastq-to-cram"]
identifier = "getwilds/ww-fastq-to-cram"
commit_hash = "7dd6c4c7c8c9fc6dcd4eb5ff8f3262cd26d5e7cc"

[repositories."getwilds/ww-star-deseq2"]
identifier = "getwilds/ww-star-deseq2"
commit_hash = "3de83fa91db1b2d1b0d91dfc20e3ca71303c8d15"

[repositories."getwilds/ww-vc-trio"]
identifier = "getwilds/ww-vc-trio"
commit_hash = "ee08634f28810e5d6fd1a904fc83f4e67821550e"

[repositories."stjudecloud/workflows"]
identifier = "stjudecloud/workflows"
commit_hash = "84bd23756563f32d144f11aa2e82a76e059a8b61"
filters = ["/template/task-templates.wdl"]

[repositories."theiagen/public_health_bioinformatics"]
identifier = "theiagen/public_health_bioinformatics"
commit_hash = "74c12d3bbced7177638fdfdc50c56f8bc40a0f5a"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/gatk-best-practices/workflows/somatic-snps-and-indels/mutec2.wdl"
message = "mutec2.wdl:112:40: error: expected input section, output section, runtime section, metadata section, parameter metadata section, conditional statement, scatter statement, call statement, or private declaration, but found `{`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/gatk-best-practices/workflows/somatic-snps-and-indels/mutec2.wdl"
message = "mutec2.wdl:112:67: error: expected declaration name, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/gatk-best-practices/workflows/somatic-snps-and-indels/mutec2.wdl"
message = "mutec2.wdl:113:62: error: expected declaration name, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/gatk-best-practices/workflows/somatic-snps-and-indels/mutec2.wdl"
message = "mutec2.wdl:114:71: error: expected declaration name, but found `*`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/gatk-best-practices/workflows/somatic-snps-and-indels/mutec2.wdl"
message = "mutec2.wdl:115:72: error: expected declaration name, but found `*`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/gatk-best-practices/workflows/somatic-snps-and-indels/mutec2.wdl"
message = "mutec2.wdl:117:5: error: expected import statement, struct definition, task definition, or workflow definition, but found `call` keyword"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/alphafold/alphafold-600.wdl"
message = "alphafold-600.wdl:110:29: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/alphafold/alphafold-600.wdl"
message = "alphafold-600.wdl:111:23: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/alphafold/alphafold-600.wdl"
message = "alphafold-600.wdl:142:29: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/alphafold/alphafold-600.wdl"
message = "alphafold-600.wdl:143:23: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/alphafold/alphafold-600.wdl"
message = "alphafold-600.wdl:174:29: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/alphafold/alphafold-600.wdl"
message = "alphafold-600.wdl:175:23: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/alphafold/alphafold-600.wdl"
message = "alphafold-600.wdl:210:29: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/alphafold/alphafold-600.wdl"
message = "alphafold-600.wdl:211:23: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/alphafold/alphafold-600.wdl"
message = "alphafold-600.wdl:244:29: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/alphafold/alphafold-600.wdl"
message = "alphafold-600.wdl:245:23: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/alphafold/alphafold-600.wdl"
message = "alphafold-600.wdl:284:29: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/alphafold/alphafold-600.wdl"
message = "alphafold-600.wdl:285:23: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/alphafold/alphafold-600.wdl"
message = "alphafold-600.wdl:323:29: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/alphafold/alphafold-600.wdl"
message = "alphafold-600.wdl:324:23: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/alphafold/alphafold-600.wdl"
message = "alphafold-600.wdl:325:28: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/alphafold/alphafold-600.wdl"
message = "alphafold-600.wdl:326:48: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/esmfold/esmfold.wdl"
message = "esmfold.wdl:58:29: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/esmfold/esmfold.wdl"
message = "esmfold.wdl:59:23: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/esmfold/esmfold.wdl"
message = "esmfold.wdl:83:29: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/esmfold/esmfold.wdl"
message = "esmfold.wdl:84:23: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/esmfold/esmfold.wdl"
message = "esmfold.wdl:85:28: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/protein-folding/workflows/esmfold/esmfold.wdl"
message = "esmfold.wdl:86:48: error: expected runtime key, but found `,`"

[[diagnostics]]
document = "biowdl/tasks:/bcftools.wdl"
message = 'bcftools.wdl:114:75: error: unknown escape sequence `\_`'

[[diagnostics]]
document = "biowdl/tasks:/bedtools.wdl"
message = 'bedtools.wdl:27:48: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/bowtie.wdl"
message = 'bowtie.wdl:63:32: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/bowtie.wdl"
message = 'bowtie.wdl:63:39: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/bowtie.wdl"
message = 'bowtie.wdl:63:46: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/bowtie.wdl"
message = 'bowtie.wdl:75:48: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/centrifuge.wdl"
message = 'centrifuge.wdl:122:57: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/centrifuge.wdl"
message = 'centrifuge.wdl:122:64: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/centrifuge.wdl"
message = 'centrifuge.wdl:199:57: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/centrifuge.wdl"
message = 'centrifuge.wdl:199:64: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/centrifuge.wdl"
message = 'centrifuge.wdl:256:57: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/centrifuge.wdl"
message = 'centrifuge.wdl:256:64: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/common.wdl"
message = 'common.wdl:275:45: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/fastqc.wdl"
message = 'fastqc.wdl:59:42: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/fastqc.wdl"
message = 'fastqc.wdl:63:54: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/fastqc.wdl"
message = 'fastqc.wdl:63:58: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/gatk.wdl"
message = 'gatk.wdl:127:57: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/gatk.wdl"
message = 'gatk.wdl:1597:41: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/hisat2.wdl"
message = 'hisat2.wdl:60:34: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/hisat2.wdl"
message = 'hisat2.wdl:60:41: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/multiqc.wdl"
message = 'multiqc.wdl:133:45: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/picard.wdl"
message = 'picard.wdl:1021:48: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/picard.wdl"
message = 'picard.wdl:1191:48: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/picard.wdl"
message = 'picard.wdl:643:51: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/picard.wdl"
message = 'picard.wdl:785:51: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/picard.wdl"
message = 'picard.wdl:900:46: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/picard.wdl"
message = 'picard.wdl:901:46: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/picard.wdl"
message = 'picard.wdl:902:49: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/sambamba.wdl"
message = 'sambamba.wdl:145:49: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/sambamba.wdl"
message = 'sambamba.wdl:157:60: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/sambamba.wdl"
message = 'sambamba.wdl:91:44: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/samtools.wdl"
message = 'samtools.wdl:238:53: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/samtools.wdl"
message = 'samtools.wdl:326:44: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/samtools.wdl"
message = 'samtools.wdl:414:44: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/samtools.wdl"
message = 'samtools.wdl:458:49: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/samtools.wdl"
message = 'samtools.wdl:470:60: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/samtools.wdl"
message = 'samtools.wdl:80:42: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/umi-tools.wdl"
message = 'umi-tools.wdl:95:49: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "biowdl/tasks:/umi.wdl"
message = 'umi.wdl:39:60: error: unknown escape sequence `\.`'

[[diagnostics]]
document = "broadinstitute/palantir-workflows:/HaplotypeMap/BuildHaplotypeMap.wdl"
message = "BuildHaplotypeMap.wdl:17:1: error: a WDL document must start with a version statement"

[[diagnostics]]
document = "broadinstitute/warp:/pipelines/skylab/scATAC/scATAC.wdl"
message = "scATAC.wdl:203:9: error: duplicate key `cpu` in runtime section"

[[diagnostics]]
document = "broadinstitute/warp:/tasks/broad/GermlineVariantDiscovery.wdl"
message = "GermlineVariantDiscovery.wdl:137:32: error: expected string, but found integer"

[[diagnostics]]
document = "broadinstitute/warp:/tasks/broad/GermlineVariantDiscovery.wdl"
message = "GermlineVariantDiscovery.wdl:65:32: error: expected string, but found integer"

[[diagnostics]]
document = "broadinstitute/warp:/tasks/broad/UltimaGenomicsWholeGenomeGermlineTasks.wdl"
message = "UltimaGenomicsWholeGenomeGermlineTasks.wdl:814:27: error: expected string, but found integer"

[[diagnostics]]
document = "broadinstitute/warp:/tasks/broad/UltimaGenomicsWholeGenomeGermlineTasks.wdl"
message = "UltimaGenomicsWholeGenomeGermlineTasks.wdl:866:27: error: expected string, but found integer"

[[diagnostics]]
document = "broadinstitute/warp:/tests/cemba/pr/CheckCembaOutputs.wdl"
message = "CheckCembaOutputs.wdl:1:1: error: a WDL document must start with a version statement"

[[diagnostics]]
document = "chanzuckerberg/czid-workflows:/workflows/index-generation/index-generation.wdl"
message = "index-generation.wdl:1:9: error: unsupported WDL version `development`"
