[package]
name = "wdl-grammar"
version = "0.6.0"
authors = ["Clay McLeod <clay.l.mcleod@gmail.com>"]
edition.workspace = true
license.workspace = true
description = "A parse tree for Workflow Description Language (WDL) documents"
homepage = "https://github.com/stjude-rust-labs/wdl"
repository = "https://github.com/stjude-rust-labs/wdl"
documentation = "https://docs.rs/wdl-grammar"

[dependencies]
logos = { workspace = true }
rowan = { workspace = true }
codespan-reporting = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
rayon = { workspace = true }
colored = { workspace = true }
codespan-reporting = { workspace = true }

[features]
codespan = ["dep:codespan-reporting"]

[[test]]
name = "parsing"
required-features = ["codespan"]
harness = false
