[package]
name = "wdl-grammar"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
env_logger.workspace = true
log.workspace = true
pest = "2.7.5"
pest_derive = "2.7.5"
