[package]
name = "wdl-doc"
version = "0.2.0"
description = "Documentation generator for Workflow Description Language (WDL) documents."
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
ammonia.workspace = true
anyhow.workspace = true
indexmap.workspace = true
maud.workspace = true
pulldown-cmark.workspace = true
pathdiff.workspace = true
tokio.workspace = true
wdl-analysis = { path = "../wdl-analysis", version = "0.7.0" }
wdl-ast = { path = "../wdl-ast", version = "0.11.0" }

[lints]
workspace = true

[[test]]
name = "doc"
harness = false
