[package]
name = "wdl-doc"
version = "0.1.0"
description = "Documentation generator for Workflow Description Language (WDL) documents."
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
html = "0.6.3"
indexmap.workspace = true
pulldown-cmark = "0.12.2"
tokio.workspace = true
wdl-analysis = { path = "../wdl-analysis", version = "0.6.0" }
wdl-ast = { path = "../wdl-ast", version = "0.10.0" }

[lints]
workspace = true

[[test]]
name = "doc"
harness = false
