[package]
name = "wdl-engine"
version = "0.4.0"
rust-version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Execution engine for Workflow Description Language (WDL) documents."
documentation = "https://docs.rs/wdl-engine"

[dependencies]
wdl-analysis = { version = "0.9.0", path = "../wdl-analysis" }
wdl-ast = { version = "0.13.0", path = "../wdl-ast" }
wdl-grammar = { version = "0.13.0", path = "../wdl-grammar" }
anyhow = { workspace = true }
crankshaft = { workspace = true }
codespan-reporting = { workspace = true, optional = true }
dirs = { workspace = true }
futures = { workspace = true }
glob = { workspace = true }
http-cache-stream-reqwest = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
nonempty = { workspace = true }
ordered-float = { workspace = true }
path-clean = { workspace = true }
petgraph = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
rev_buf_reader = "0.3.0"
rowan = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }
shellexpand = { workspace = true }
sysinfo = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
colored = { workspace = true }
pretty_assertions = { workspace = true }
rayon = { workspace = true }
walkdir = { workspace = true }

[lints]
workspace = true

[features]
default = []
codespan = ["wdl-ast/codespan"]
codespan-reporting = ["codespan", "dep:codespan-reporting"]

[[test]]
name = "inputs"
required-features = ["codespan-reporting"]
harness = false

[[test]]
name = "tasks"
required-features = ["codespan-reporting"]
harness = false

[[test]]
name = "workflows"
required-features = ["codespan-reporting"]
harness = false
