name: CI

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Update Rust
        run: rustup update nightly && rustup default nightly
      - name: Install rustfmt
        run: rustup component add rustfmt
      - run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Update Rust
        run: rustup update nightly && rustup default nightly
      - name: Install clippy
        run: rustup component add clippy
      - run: cargo clippy --all-features -- --deny warnings

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Update Rust
        run: rustup update nightly && rustup default nightly
      - run: cargo test --all-features

  test-examples:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Update Rust
        run: rustup update nightly && rustup default nightly
      - run: cargo test --all-features --examples

  docs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Update Rust
        run: rustup update nightly && rustup default nightly
      - run: cargo doc

  gauntlet:
    runs-on: ubuntu-22.04
    env:
      CACHE_DIR: ~/.config/wdl-grammar
    steps:
      - uses: actions/checkout@v3
      - name: Update Rust
        run: rustup update nightly && rustup default nightly
      - run: cargo run --release --bin wdl-gauntlet