name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update nightly && rustup default nightly
      - name: Install rustfmt
        run: rustup component add rustfmt
      - run: cargo fmt -- --check

  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - name: Install clippy
        run: rustup component add clippy
      - run: cargo clippy --all-features -- --deny warnings

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-shellcheck
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - name: Setup Docker (Mac)
        if: ${{'macos-latest' == matrix.os}}
        run: |
          brew update
          brew install docker
          brew install qemu
          brew install colima
          brew install lima-additional-guestagents
          # M1 and M2 Macs that the Github Actions supplies don't support nested virtualization. This forces x86 emulation to get around this
          #--mount /private is necessary here in order to give docker access to mac's temp directory for tests
          colima start --mount /private --memory 4 --network-address --arch x86_64
          echo "DOCKER_HOST=unix:///Users/runner/.colima/docker.sock" >> $GITHUB_ENV
      - name: Setup WSL (Windows)
        if: ${{'windows-latest' == matrix.os}}
        uses: Vampire/setup-wsl@v5
      - name: Install Podman (Windows)
        if: ${{'windows-latest' == matrix.os}}
        run: |
          curl -L --url "https://github.com/containers/podman/releases/download/v5.5.1/podman-5.5.1-setup.exe" -o Podman.exe
          Start-Process Podman.exe -Wait -ArgumentList "/norestart /passive" -Verb runAs;
          Add-Content $env:GITHUB_PATH "C:\Program Files\RedHat\Podman\"
      - name: Startup Docker (Windows)
        if: ${{'windows-latest' == matrix.os}}
        run: |
          podman machine init
          podman machine set --rootful
          podman machine start
          Add-Content $env:GITHUB_ENV "DOCKER_HOST=npipe:////./pipe/podman-machine-default"
      - name: Run tests
        run: cargo test --all-features
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: docker pull ubuntu:latest
        if: runner.os == 'Linux'
      - run: cargo test --all --all-features
      - run: cargo test --all-features --examples

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - run: cargo doc

  gauntlet:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - run: git config --global core.autocrlf false
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - run: cargo run --release --bin gauntlet

  arena:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-shellcheck
      - run: git config --global core.autocrlf false
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - run: cargo run --release --bin gauntlet -- --arena

  workspace-lints-enabled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - run: cargo install cargo-workspace-lints --locked
      - run: cargo workspace-lints

  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - run: cargo install cargo-deny --locked
      - run: cargo deny check

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - name: Install cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      - name: Install cargo-msrv
        run: cargo binstall -y --version 0.16.0-beta.23 cargo-msrv
      - name: Verify the MSRV
        working-directory: ./wdl
        run: cargo msrv verify --output-format minimal --all-features

  udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - name: Install cargo-udeps
        run: cargo install cargo-udeps --locked
      - name: Ensure no unused dependencies
        run: cargo +nightly udeps
