name: 'Auto Assign'
on:
  pull_request_target:
    types: [opened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  add-owner:
    runs-on: ubuntu-24.04
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      pull-requests: write
    steps:
      - name: run
        uses: kentaro-m/auto-assign-action@f4648c0a9fdb753479e9e75fc251f507ce17bb7e # v2.0.0
        with:
          configuration-path: ".github/auto_assign.yml"
          repo-token: '${{ github.token }}'
  add-reviewers:
    runs-on: ubuntu-24.04
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      pull-requests: write
    steps:
      - name: run
        uses: kentaro-m/auto-assign-action@f4648c0a9fdb753479e9e75fc251f507ce17bb7e # v2.0.0
        with:
          configuration-path: ".github/auto_assign.yml"
          repo-token: '${{ github.token }}'