name: Release

on:
  workflow_dispatch:
    inputs:
      crate:
        description: Crate to bump (anything which depends on this crate will also be bumped)
        type: choice
        default: wdl-grammar
        options:
          - wdl-grammar
          - wdl-ast
          - wdl-lint
          - wdl-analysis
          - wdl-lsp
          - wdl

jobs:
  bump:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - run: cargo run --release --bin ci -- bump --crates-to-bump ${{ inputs.crate }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: chore/bump
          title: "release: bump versions"